In [1]:
#NUMPY cash course

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [5]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(6.0)

array([0., 1., 2., 3., 4., 5.])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10)

array([], dtype=int64)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [19]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [23]:
np.zeros((5,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [26]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [27]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [28]:
np.twos(4)

AttributeError: module 'numpy' has no attribute 'twos'